// packages/vue/lib/components/BubbleChart/BubbleChart.vue
<script setup lang="ts" generic="T">
import { computed, ref, useSlots, useTemplateRef } from "vue";
import { Position, Scatter } from "@unovis/ts";
import {
  VisXYContainer,
  VisScatter,
  VisAxis,
  VisTooltip,
  VisBulletLegend,
} from "@unovis/vue";
import { BubbleChartProps } from "./BubbleChart";
import { LegendPosition } from "../../enums";
import { getFirstPropertyValue } from "../../utils";
import { useChartAccessibility, generateChartLabel } from "../../composables/useChartAccessibility";

import Tooltip from "../Tooltip.vue";

import type { NumericAccessor } from "@unovis/ts";

const props = withDefaults(defineProps<BubbleChartProps<T>>(), {
  duration: 600,
  hideXAxis: false,
  hideYAxis: false,
  xLabel: "",
  yLabel: "",
  xGridLine: false,
  yGridLine: true,
  xDomainLine: true,
  yDomainLine: true,
  xTickLine: true,
  yTickLine: true,
  xNumTicks: undefined,
  yNumTicks: undefined,
  xExplicitTicks: undefined,
  minMaxTicksOnly: false,
  hideLegend: false,
  legendPosition: LegendPosition.BottomCenter,
  padding: () => ({ top: 5, right: 5, bottom: 5, left: 5 }),
  hideTooltip: false,
  crosshairConfig: () => ({
    color: "#666",
  }),
  legendStyle: undefined,
  tooltip: () => ({
    followCursor: true,
  }),
});

const slots = useSlots();
const slotWrapperRef = useTemplateRef<HTMLDivElement>("slotWrapper");
const hoverValues = ref<T>();

const accessibilityAttrs = useChartAccessibility(
  props,
  generateChartLabel("Bubble", props.categories, props.data.length)
);

const x: NumericAccessor<T> = props.xAccessor!;
const y: NumericAccessor<T> = props.yAccessor!;
const size: NumericAccessor<T> =
  props.sizeAccessor ||
  ((d: any) => (typeof d.comments === "number" ? d.comments : 1));

const color = (d: T) => {
  if (!props.categories || !props.categoryKey) {
    console.warn(
      "BubbleChart: categories and categoryKey are required for color mapping"
    );
    return "#cccccc";
  }

  const categoryValue = String(d[props.categoryKey as keyof T]);
  let categoryColor = props.categories[categoryValue]?.color;

  if (Object.keys(props.categories).length === 1) {
    categoryColor =
      props.categories[props.categoryKey as keyof typeof props.categories]
        ?.color;
  }

  if (!categoryColor) {
    console.warn(
      `BubbleChart: No color defined for category "${categoryValue}"`
    );
    return "#cccccc";
  }

  return categoryColor;
};

const emit = defineEmits<{
  (e: "click", event: MouseEvent, values?: T): void;
}>();

function onCrosshairUpdate(d: T): string {
  hoverValues.value = d;
  return generateTooltipContent(d);
}

function generateTooltipContent(d: T): string {
  if (typeof window === "undefined") {
    return "";
  }
  if (slotWrapperRef.value) {
    return slotWrapperRef.value.innerHTML;
  }
  return "";
}

const triggers = {
  [Scatter.selectors.point]: onCrosshairUpdate,
};

const isLegendTop = computed(() => props.legendPosition.startsWith("top"));

const legendAlignment = computed(() => {
  if (props.legendPosition.includes("left")) return "flex-start";
  if (props.legendPosition.includes("right")) return "flex-end";
  return "center";
});
</script>

<template>
  <div
    v-bind="accessibilityAttrs"
    :style="{
      display: 'flex',
      flexDirection: isLegendTop ? 'column-reverse' : 'column',
      gap: 'var(--vis-legend-spacing)',
    }"
  >
    <VisXYContainer
      :data="props.data"
      :height="props.height || 600"
      :padding="props.padding"
      :duration="duration"
      :scaleByDomain="true"
      @click="emit('click', $event, hoverValues)"
    >
      <VisTooltip
        v-if="!props.hideTooltip"
        :triggers="triggers"
        :followCursor="props.tooltip.followCursor"
        :show-delay="props.tooltip.showDelay"
        :hide-delay="props.tooltip.hideDelay"
      />
      <VisScatter
        :x="x"
        :y="y"
        :color="color"
        :size="size"
        :labelPosition="props.labelPosition || Position.Bottom"
        :sizeRange="props.sizeRange || [1, 20]"
        :opacity="props.opacity"
        cursor="pointer"
      />
      <VisAxis
        v-if="!props.hideXAxis"
        type="x"
        :label="props.xLabel"
        :tickFormat="props.xFormatter"
        :gridLine="props.xGridLine"
        :domainLine="!!props.xDomainLine"
        :tickLine="props.xTickLine"
        :numTicks="props.xNumTicks"
        :tickValues="props.xExplicitTicks"
        :minMaxTicksOnly="props.minMaxTicksOnly"
        :duration="props.duration"
        v-bind="xAxisConfig"
      />
      <VisAxis
        v-if="!props.hideYAxis"
        type="y"
        :label="props.yLabel"
        :tickFormat="props.yFormatter"
        :gridLine="props.yGridLine"
        :domainLine="!!props.yDomainLine"
        :tickLine="props.yTickLine"
        :numTicks="props.yNumTicks"
        :duration="props.duration"
        v-bind="yAxisConfig"
      />
    </VisXYContainer>

    <div
      v-if="!props.hideLegend"
      :style="{
        display: 'flex',
        justifyContent: legendAlignment,
      }"
    >
      <VisBulletLegend
        class="bulletLegendOverrides"
        :style="[
          props.legendStyle,
          'display: flex; gap: var(--vis-legend-spacing);',
        ]"
        :items="
          Object.values(props.categories).map((item) => ({
            ...item,
            color: Array.isArray(item.color) ? item.color[0] : item.color,
          }))
        "
      />
    </div>

    <div ref="slotWrapper" class="hidden">
      <slot v-if="slots.tooltip" name="tooltip" :values="hoverValues" />
      <slot v-else-if="hoverValues" name="fallback">
        <Tooltip
          :data="hoverValues"
          :categories="props.categories || {}"
          :title-formatter="props.tooltipTitleFormatter"
          :yFormatter="props.yFormatter"
        />
      </slot>
    </div>
  </div>
</template>

// packages/angular/projects/lib/src/lib/bubble-chart/bubble-chart.component.ts
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  output,
  signal,
  viewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  VisXYContainerModule,
  VisScatterModule,
  VisAxisModule,
  VisTooltipModule,
  VisBulletLegendModule,
} from '@unovis/angular';
import { Position, Scatter, type NumericAccessor } from '@unovis/ts';
import { LegendPosition, BulletLegendItemInterface, AxisConfig, CrosshairConfig } from '../types';
import { TooltipComponent } from '../tooltip/tooltip.component';

@Component({
  selector: 'ngx-bubble-chart',
  standalone: true,
  imports: [
    CommonModule,
    VisXYContainerModule,
    VisScatterModule,
    VisAxisModule,
    VisTooltipModule,
    VisBulletLegendModule,
    TooltipComponent,
  ],
  template: `
    <div
      [style.display]="'flex'"
      [style.flexDirection]="isLegendTop() ? 'column-reverse' : 'column'"
      [style.gap]="'var(--vis-legend-spacing)'"
    >
      <vis-xy-container
        [data]="data()"
        [height]="height()"
        [padding]="padding()"
        [scaleByDomain]="true"
        (click)="onClick($event)"
      >
        @if (!hideTooltip()) {
          <vis-tooltip [triggers]="tooltipTriggers"></vis-tooltip>
        }

        <vis-scatter
          [x]="xAccessor()"
          [y]="yAccessor()"
          [color]="colorAccessor"
          [size]="sizeAccessorFn()"
          [labelPosition]="labelPosition() || Position.Bottom"
          [sizeRange]="sizeRange() || [1, 20]"
          cursor="pointer"
        ></vis-scatter>

        @if (!hideXAxis()) {
          <vis-axis
            type="x"
            [label]="xLabel()"
            [tickFormat]="xFormatterFn"
            [gridLine]="xGridLine()"
            [domainLine]="!!xDomainLine()"
            [tickLine]="xTickLine()"
            [numTicks]="xNumTicks()"
            [tickValues]="xExplicitTicks()"
            [minMaxTicksOnly]="minMaxTicksOnly()"
          ></vis-axis>
        }

        @if (!hideYAxis()) {
          <vis-axis
            type="y"
            [label]="yLabel()"
            [tickFormat]="yFormatterFn"
            [gridLine]="yGridLine()"
            [domainLine]="!!yDomainLine()"
            [tickLine]="yTickLine()"
            [numTicks]="yNumTicks()"
          ></vis-axis>
        }
      </vis-xy-container>

      @if (!hideLegend()) {
        <div
          [style.display]="'flex'"
          [style.justifyContent]="legendAlignment()"
        >
          <vis-bullet-legend
            [items]="legendItems()"
          ></vis-bullet-legend>
        </div>
      }

      <div #tooltipWrapper style="display: none">
        @if (hoverValues()) {
          <ngx-tooltip
            [data]="hoverValues()!"
            [categories]="categories() || {}"
            [titleFormatter]="tooltipTitleFormatter()"
            [yFormatter]="yFormatter()"
          ></ngx-tooltip>
        }
      </div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BubbleChartComponent<T extends Record<string, any>> {
  readonly data = input.required<T[]>();
  readonly height = input<number>(600);
  readonly padding = input<{ top: number; right: number; bottom: number; left: number }>({
    top: 5,
    right: 5,
    bottom: 5,
    left: 5,
  });
  readonly categories = input<Record<string, BulletLegendItemInterface>>({});
  readonly categoryKey = input<keyof T>();
  readonly xAccessor = input<NumericAccessor<T>>();
  readonly yAccessor = input<NumericAccessor<T>>();
  readonly sizeAccessor = input<NumericAccessor<T>>();
  readonly labelPosition = input<Position>();
  readonly sizeRange = input<[number, number]>();
  readonly xLabel = input<string>('');
  readonly yLabel = input<string>('');
  readonly xFormatter = input<(tick: number | Date, i?: number, ticks?: (number | Date)[]) => string>();
  readonly yFormatter = input<(tick: number | Date, i?: number, ticks?: (number | Date)[]) => string>();
  readonly tooltipTitleFormatter = input<(data: T) => string | number>();
  readonly xNumTicks = input<number>();
  readonly yNumTicks = input<number>();
  readonly xExplicitTicks = input<any[]>();
  readonly minMaxTicksOnly = input<boolean>(false);
  readonly hideXAxis = input<boolean>(false);
  readonly hideYAxis = input<boolean>(false);
  readonly xGridLine = input<boolean>(false);
  readonly yGridLine = input<boolean>(true);
  readonly xDomainLine = input<boolean>(true);
  readonly yDomainLine = input<boolean>(true);
  readonly xTickLine = input<boolean>(true);
  readonly yTickLine = input<boolean>(true);
  readonly hideTooltip = input<boolean>(false);
  readonly hideLegend = input<boolean>(false);
  readonly legendPosition = input<LegendPosition>(LegendPosition.BottomCenter);
  readonly legendStyle = input<Record<string, string>>();
  readonly crosshairConfig = input<CrosshairConfig>({ color: '#666' });
  readonly xAxisConfig = input<AxisConfig>();
  readonly yAxisConfig = input<AxisConfig>();

  readonly click = output<{ event: MouseEvent; values?: T }>();

  readonly tooltipWrapper = viewChild<ElementRef<HTMLDivElement>>('tooltipWrapper');
  readonly hoverValues = signal<T | undefined>(undefined);

  readonly Position = Position;

  readonly isLegendTop = computed(() => this.legendPosition().startsWith('top'));

  readonly legendAlignment = computed(() => {
    const pos = this.legendPosition();
    if (pos.includes('left')) return 'flex-start';
    if (pos.includes('right')) return 'flex-end';
    return 'center';
  });

  readonly legendItems = computed(() => {
    const cats = this.categories();
    return Object.values(cats).map((item) => ({
      ...item,
      color: Array.isArray(item.color) ? item.color[0] : item.color,
    }));
  });

  readonly sizeAccessorFn = computed(() => {
    const accessor = this.sizeAccessor();
    if (accessor) return accessor;
    return (d: any) => (typeof d.comments === 'number' ? d.comments : 1);
  });

  colorAccessor = (d: T): string | null | undefined => {
    const cats = this.categories();
    const catKey = this.categoryKey();
    if (!cats || !catKey) {
      return '#cccccc';
    }

    const categoryValue = String(d[catKey as keyof T]);
    let categoryColor = cats[categoryValue]?.color;

    if (Object.keys(cats).length === 1) {
      categoryColor = cats[catKey as keyof typeof cats]?.color;
    }

    if (!categoryColor) {
      return '#cccccc';
    }

    // Ensure we return a string, not an array
    return Array.isArray(categoryColor) ? categoryColor[0] : categoryColor;
  };

  xFormatterFn = (tick: number | Date, i: number, ticks: (number | Date)[]) => {
    const formatter = this.xFormatter();
    return formatter ? formatter(tick, i, ticks) : String(tick);
  };

  yFormatterFn = (tick: number | Date, i: number, ticks: (number | Date)[]) => {
    const formatter = this.yFormatter();
    return formatter ? formatter(tick, i, ticks) : String(tick);
  };

  tooltipTriggers: Record<string, (d: T) => string> = {
    [Scatter.selectors.point]: (d: T) => {
      this.onCrosshairUpdate(d);
      return d ? this.tooltipWrapper()?.nativeElement.innerHTML ?? '' : '';
    },
  };

  onCrosshairUpdate(d: T): void {
    this.hoverValues.set(d);
    this.cdr.detectChanges();
  }

  onClick(event: MouseEvent): void {
    this.click.emit({ event, values: this.hoverValues() });
  }

  private cdr = inject(ChangeDetectorRef);
}
